### ISSUE TITLE
Add JSX support

### ISSUE THREAD

**Issue by yosbelms** [yosbelms/ramdascript#7]

**Comment by quangv** [comment]
Fyi, instead of JSX,  [r-dom](https://github.com/uber/r-dom) is good alternative.

I am using `r-dom` with coffee-script (and am looking into ramdascript), I liked it enough to make [dr-dom](https://github.com/quangv/dr-dom) which is a useful wrapper to r-dom. (version 0.0.1 prolly can't be consumed via npm yet)

**Comment by yosbelms** [comment]
Very nice lib, some time ago I made a little lib around the same concept but sincerely I've never used it with RamdaScript. https://github.com/yosbelms/hfactory

**Comment by yosbelms** [comment]
Actually I think that with libs like `r-dom`, `dr-dom` and `hfactory`, JSX is not priority any more. I will close this issue for now
